### ISSUE TITLE
[DOCS] Improve the README

### ISSUE THREAD

**Issue by devXprite** [devXprite/GitVio#4]

**Comment by naman-ng** [comment]
Hi, I'll be taking this on, pls do tell if you have something specific improvement in mind.

**Comment by naman-ng** [comment]
The favicon is the logo of the project right? The img at the starting of readme file is just a filler I suppose?

**Comment by devXprite** [comment]
> The favicon is the logo of the project right? The img at the starting of readme file is just a filler I suppose?

Yes that image was just to fill the Readme you can replace it with favicon.  And if possible, try to add a short description about the project.

**Comment by naman-ng** [comment]
Also, do you want me to add the contributors section.

**Comment by devXprite** [comment]
> Also, do you want me to add the contributors section.

You will automatically added to the [Contributors section](https://github.com/devXprite/GitVio/graphs/contributors)  after merging PR.
